#!/usr/bin/env -S uv run --script
# /// script
# requires-python = ">=3.11"
# dependencies = ["pillow==11.3.0"]
# ///
"""Generate linkfw/src/kiro_body.{c,h} from the official kiro-ghost.svg.

Differences from the original AMOLED-1.8 generator:
  * larger target height (the round 466 px screen can carry a bigger ghost);
  * the alpha channel is softened by a sub-pixel blur before compositing, so the
    edge gets a 2-3 step ramp instead of a single 50 % pixel — that is what kills
    the visible staircase on curved edges;
  * alpha below --floor is clamped to zero. On an emissive AMOLED a faint halo
    pixel (grey ~16) still lights its R/G/B subpixels individually and reads as a
    coloured speck, so the ramp must start at a substantial value;
  * edge pixels are forced to neutral grey before RGB565 quantisation, so no
    colour fringing can appear in the 5/6/5 rounding.

The face always draws on black, so compositing onto black here is exact.
Requires rsvg-convert (brew install librsvg).

Usage: linkfw/tools/gen_kiro_body.py [--height 300] [--svg PATH]
"""
from __future__ import annotations

import argparse
import os
import re
import subprocess
import tempfile

from PIL import Image, ImageFilter

DEFAULT_SVG = os.path.expanduser(
    "~/work/projects/260712-ESP32-S3-Touch-AMOLED-1.8/amoled-apps/assets/kiro-ghost.svg")
OUT_C = os.path.join(os.path.dirname(os.path.dirname(os.path.abspath(__file__))), "src", "kiro_body.c")
OUT_H = OUT_C[:-2] + ".h"

RENDER_W = 2000           # rasterise well above target, then downscale
VIEW_W, VIEW_H = 250, 470  # widened view box so the bottom tail is not clipped


def render(svg_text: str, w: int, h: int) -> Image.Image:
    with tempfile.NamedTemporaryFile("w", suffix=".svg", delete=False) as f:
        f.write(svg_text)
        path = f.name
    png = path + ".png"
    subprocess.run(["rsvg-convert", "-w", str(w), "-h", str(h), path, "-o", png], check=True)
    img = Image.open(png).convert("RGBA")
    os.remove(path)
    os.remove(png)
    return img


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("--height", type=int, default=258)
    ap.add_argument("--blur", type=float, default=0.35, help="sub-pixel blur on alpha")
    ap.add_argument("--floor", type=int, default=40, help="alpha below this becomes fully transparent")
    ap.add_argument("--svg", default=DEFAULT_SVG)
    a = ap.parse_args()

    src = open(a.svg).read()
    src = src.replace('viewBox="0 0 250 441"', f'viewBox="0 0 {VIEW_W} {VIEW_H}"')
    src = re.sub(r'height="441"', f'height="{VIEW_H}"', src)

    body_svg = re.sub(r'<path[^>]*fill="black"[^>]*/>\s*', "", src)      # body only
    eye_paths = re.findall(r'<path[^>]*fill="black"[^>]*/>', src)
    eyes_svg = re.sub(r"(<svg[^>]*>).*?(</svg>)",
                      lambda m: m.group(1) + "".join(eye_paths) + m.group(2), src, flags=re.S)

    rw = RENDER_W
    rh = round(rw * VIEW_H / VIEW_W)
    body = render(body_svg, rw, rh)
    eyes = render(eyes_svg, rw, rh)

    bbox = body.split()[3].point(lambda v: 255 if v > 16 else 0).getbbox()
    L, T, R, B = bbox
    scale = a.height / (B - T)
    fin_w, fin_h = round((R - L) * scale), a.height

    crop = body.crop(bbox).resize((fin_w, fin_h), Image.LANCZOS)
    alpha = crop.split()[3].filter(ImageFilter.GaussianBlur(a.blur))
    # Clamp the faint tail to black and stretch what remains, so the ramp has
    # few but meaningful steps instead of a dim halo of coloured-looking specks.
    floor = max(0, min(200, a.floor))
    alpha = alpha.point(lambda v: 0 if v <= floor else min(255, round((v - floor) * 255 / (255 - floor))))
    flat = Image.new("RGB", (fin_w, fin_h), (0, 0, 0))
    flat.paste(Image.new("RGB", (fin_w, fin_h), (255, 255, 255)), (0, 0), alpha)
    px = flat.load()

    # eye centres / size, in the cropped+scaled coordinate system
    ea = eyes.split()[3]
    pts = [(x, y) for y in range(eyes.height) for x in range(eyes.width) if ea.getpixel((x, y)) > 40]
    xs = sorted(p[0] for p in pts)
    midx = xs[len(xs) // 2]
    groups = ([p for p in pts if p[0] < midx], [p for p in pts if p[0] >= midx])
    centres = []
    for g in groups:
        cx = sum(p[0] for p in g) / len(g)
        cy = sum(p[1] for p in g) / len(g)
        gw = max(p[0] for p in g) - min(p[0] for p in g)
        gh = max(p[1] for p in g) - min(p[1] for p in g)
        centres.append((cx, cy, gw, gh))
    to_fin = lambda cx, cy: (round((cx - L) * scale), round((cy - T) * scale))
    (lx, ly), (rx, _) = to_fin(*centres[0][:2]), to_fin(*centres[1][:2])
    eye_w, eye_h = round(centres[0][2] * scale), round(centres[0][3] * scale)

    def rgb565(r: int, g: int, b: int) -> int:
        return ((r >> 3) << 11) | ((g >> 2) << 5) | (b >> 3)

    with open(OUT_H, "w") as f:
        f.write("// AUTO-GENERATED by linkfw/tools/gen_kiro_body.py. Do not edit.\n#pragma once\n"
                "#include <stdint.h>\n\n"
                f"#define KIRO_BODY_W {fin_w}\n#define KIRO_BODY_H {fin_h}\n"
                f"#define KIRO_EYE_L_X {lx}\n#define KIRO_EYE_L_Y {ly}\n"
                f"#define KIRO_EYE_R_X {rx}\n#define KIRO_EYE_R_Y {ly}\n"
                f"#define KIRO_EYE_W {eye_w}\n#define KIRO_EYE_H {eye_h}\n"
                "extern const uint16_t kiro_body[KIRO_BODY_W * KIRO_BODY_H];\n")

    with open(OUT_C, "w") as f:
        f.write("// AUTO-GENERATED by linkfw/tools/gen_kiro_body.py from assets/kiro-ghost.svg\n"
                "// Kiro ghost body (white on black, no eyes), RGB565 little endian. Do not edit.\n"
                '#include "kiro_body.h"\n\n'
                f"const uint16_t kiro_body[{fin_w * fin_h}] = {{\n")
        for y in range(fin_h):
            row = []
            for x in range(fin_w):
                r, g, b = px[x, y]
                v = (r + g + b) // 3           # neutral grey: no colour fringe after quantisation
                row.append(f"0x{rgb565(v, v, v):04X}")
            for i in range(0, len(row), 16):
                f.write("  " + ",".join(row[i:i + 16]) + ",\n")
        f.write("};\n")

    print(f"body {fin_w}x{fin_h}  eyes L({lx},{ly}) R({rx},{ly}) {eye_w}x{eye_h}  "
          f"{fin_w * fin_h * 2 / 1024:.0f} KiB flash")


if __name__ == "__main__":
    main()
