// AUTO-GENERATED by linkfw/tools/gen_kiro_body.py. Do not edit.
#pragma once
#include <stdint.h>

#define KIRO_BODY_W 213
#define KIRO_BODY_H 258
#define KIRO_EYE_L_X 118
#define KIRO_EYE_L_Y 92
#define KIRO_EYE_R_X 162
#define KIRO_EYE_R_Y 92
#define KIRO_EYE_W 25
#define KIRO_EYE_H 41
extern const uint16_t kiro_body[KIRO_BODY_W * KIRO_BODY_H];
